# windows:SUPPORTED_Windows7
#
# Specifies the e-mail address to be used when sending the log files that are generated by NCA to the network administrator. 
# 
# When the user sends the log files to the Administrator, NCA uses the default e-mail client to open a new message with the support email address in the To: field of the message, then attaches the generated log files as a .html file. The user can review the message and add additional information before sending the message.
# 
Support Email Address:
  lgpo.set:
  - name: SupportEmail
  - setting:
      SupportEmail_Control: text-placeholder
  - policy_class: Machine
